# Generated by Django 4.2.4 on 2023-08-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=50)),
                ('day', models.IntegerField()),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreTimezone',
            fields=[
                ('store_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timezone_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=50)),
                ('timestamp_utc', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('business_hours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.businesshours')),
            ],
        ),
        migrations.AddField(
            model_name='businesshours',
            name='timezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.storetimezone'),
        ),
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together={('store_id', 'day')},
        ),
    ]
