# Generated by Django 4.2.4 on 2023-08-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together=set(),
        ),
    ]
