# Generated by Django 4.2.4 on 2023-08-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_businesshours_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storestatus',
            name='business_hours',
        ),
    ]
