# Generated by Django 4.2.4 on 2023-08-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_storestatus_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='store_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='store_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['store_id'], name='monitor_bus_store_i_97f0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='storestatus',
            index=models.Index(fields=['store_id'], name='monitor_sto_store_i_9a034e_idx'),
        ),
    ]
